import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { LuaParser } from "./luaParser";

describe("LuaParser", () => {
  it("parses the SavedVariables values used by the addon", () => {
    const parsed = new LuaParser(`
      -- generated by World of Warcraft
      WowDashboardDB = {
        ["enabled"] = true,
        ["count"] = -12.5,
        ["label"] = "line\\nvalue",
        ["values"] = { 1, 2, 3 },
        ["missing"] = nil,
      }
    `).parseFile();

    assert.deepEqual(parsed, {
      enabled: true,
      count: -12.5,
      label: "line\nvalue",
      values: [1, 2, 3],
      missing: null,
    });
  });

  it("scans large numeric arrays without slicing the unparsed tail for every value", () => {
    const values = Array.from({ length: 10_000 }, (_, index) => String(index)).join(",");
    const parsed = new LuaParser(`WowDashboardDB = { ["values"] = { ${values} } }`).parseFile();

    assert.ok(parsed);
    const parsedValues = parsed.values as number[];
    assert.equal(parsedValues.length, 10_000);
    assert.equal(parsedValues.at(-1), 9_999);
  });
});
