/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterCharacterIdRouteImport } from './routes/character.$characterId'
import { Route as AuthElectronLoginRouteImport } from './routes/auth/electron-login'
import { Route as AuthElectronCallbackRouteImport } from './routes/auth/electron-callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCharacterIdRoute = CharacterCharacterIdRouteImport.update({
  id: '/character/$characterId',
  path: '/character/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthElectronLoginRoute = AuthElectronLoginRouteImport.update({
  id: '/auth/electron-login',
  path: '/auth/electron-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthElectronCallbackRoute = AuthElectronCallbackRouteImport.update({
  id: '/auth/electron-callback',
  path: '/auth/electron-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/auth/electron-callback': typeof AuthElectronCallbackRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/auth/electron-callback': typeof AuthElectronCallbackRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/auth/electron-callback': typeof AuthElectronCallbackRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/scoreboard'
    | '/settings'
    | '/auth/electron-callback'
    | '/auth/electron-login'
    | '/character/$characterId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/scoreboard'
    | '/settings'
    | '/auth/electron-callback'
    | '/auth/electron-login'
    | '/character/$characterId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/scoreboard'
    | '/settings'
    | '/auth/electron-callback'
    | '/auth/electron-login'
    | '/character/$characterId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ScoreboardRoute: typeof ScoreboardRoute
  SettingsRoute: typeof SettingsRoute
  AuthElectronCallbackRoute: typeof AuthElectronCallbackRoute
  AuthElectronLoginRoute: typeof AuthElectronLoginRoute
  CharacterCharacterIdRoute: typeof CharacterCharacterIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$characterId': {
      id: '/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof CharacterCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/electron-login': {
      id: '/auth/electron-login'
      path: '/auth/electron-login'
      fullPath: '/auth/electron-login'
      preLoaderRoute: typeof AuthElectronLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/electron-callback': {
      id: '/auth/electron-callback'
      path: '/auth/electron-callback'
      fullPath: '/auth/electron-callback'
      preLoaderRoute: typeof AuthElectronCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ScoreboardRoute: ScoreboardRoute,
  SettingsRoute: SettingsRoute,
  AuthElectronCallbackRoute: AuthElectronCallbackRoute,
  AuthElectronLoginRoute: AuthElectronLoginRoute,
  CharacterCharacterIdRoute: CharacterCharacterIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
