/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ScoreboardRouteImport } from "./routes/scoreboard";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CharacterCharacterIdRouteImport } from "./routes/character.$characterId";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const ScoreboardRoute = ScoreboardRouteImport.update({
  id: "/scoreboard",
  path: "/scoreboard",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CharacterCharacterIdRoute = CharacterCharacterIdRouteImport.update({
  id: "/character/$characterId",
  path: "/character/$characterId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/scoreboard": typeof ScoreboardRoute;
  "/character/$characterId": typeof CharacterCharacterIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/scoreboard": typeof ScoreboardRoute;
  "/character/$characterId": typeof CharacterCharacterIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/scoreboard": typeof ScoreboardRoute;
  "/character/$characterId": typeof CharacterCharacterIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/scoreboard" | "/character/$characterId" | "/api/auth/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/scoreboard" | "/character/$characterId" | "/api/auth/$";
  id: "__root__" | "/" | "/dashboard" | "/scoreboard" | "/character/$characterId" | "/api/auth/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  ScoreboardRoute: typeof ScoreboardRoute;
  CharacterCharacterIdRoute: typeof CharacterCharacterIdRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/scoreboard": {
      id: "/scoreboard";
      path: "/scoreboard";
      fullPath: "/scoreboard";
      preLoaderRoute: typeof ScoreboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/character/$characterId": {
      id: "/character/$characterId";
      path: "/character/$characterId";
      fullPath: "/character/$characterId";
      preLoaderRoute: typeof CharacterCharacterIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ScoreboardRoute: ScoreboardRoute,
  CharacterCharacterIdRoute: CharacterCharacterIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
