FROM node:20-slim AS base

ENV PNPM_HOME=/pnpm
ENV PATH="${PNPM_HOME}:${PATH}"

RUN corepack enable

WORKDIR /app

FROM base AS build

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm -F @wow-dashboard/api check-types

FROM base AS runtime

ENV NODE_ENV=production

COPY --from=build --chown=node:node /app /app

USER node

EXPOSE 3000

CMD ["pnpm", "-F", "@wow-dashboard/api", "start"]
